{{- if and .Values.grafana .Values.grafana.install }}
{{- if .Values.grafana.disableDefaultAdminSecret }}
{{- if not (hasKey .Values.grafana "adminCredentialsSecret") }}
{{- fail "grafana.adminCredentialsSecret is required when grafana.disableDefaultAdminSecret=true" }}
{{- end }}
{{- if not .Values.grafana.adminCredentialsSecret.adminPassword }}
{{- fail "grafana.adminCredentialsSecret.adminPassword is required when grafana.disableDefaultAdminSecret=true" }}
{{- end }}
{{- $grafanaName := "grafana" }}
{{- if .Values.grafana.name }}
{{- $grafanaName = .Values.grafana.name }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $grafanaName }}-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $grafanaName }}-admin-credentials
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: Helm
    {{- if .Values.grafana.adminCredentialsSecret.labels }}
    {{- toYaml .Values.grafana.adminCredentialsSecret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.grafana.adminCredentialsSecret.annotations }}
  annotations:
    {{- toYaml .Values.grafana.adminCredentialsSecret.annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.adminCredentialsSecret.adminUser | default "admin" | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.adminCredentialsSecret.adminPassword | quote }}
{{- end }}
{{- end }}
