name: Run Monitoring Pipeline

on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
    - '.github/**'
    - 'docs/**'
    - 'CODE-OF-CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'
  workflow_dispatch: {}

jobs:
  Wait-for-images:
    if: |
      (
        github.event_name != 'pull_request' ||
        (
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'renovate[bot]'
        )
      )
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for build.yaml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@release/v2.0.5
        id: wait
        with:
          workflow: docker-dev.yml
          token: ${{ secrets.GITHUB_TOKEN }}

  Monitoring-Pipeline:
    needs: Wait-for-images
    if: |
      needs.Wait-for-images.outputs.conclusion == 'success' &&
      (
        github.event_name != 'pull_request' ||
        (
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'renovate[bot]'
        )
      )
    uses: Netcracker/qubership-test-pipelines/.github/workflows/monitoring.yaml@monitoring
    with:
      service_branch: ${{ github.sha }}
      versions_file: '.github/versions.yaml'
      pipeline_branch: 'monitoring' #this value must match the value after '@' in 'uses'
      repository_name: '${{ github.repository_owner }}/qubership-monitoring-operator'
      kind-layout: 'single-node'
